### ISSUE TITLE
When adding a 2nd comment, the text from the first stays in the input box

### ISSUE THREAD

**Issue by antmachine** [ConceptYard/code_project#1]
![image](https://cloud.githubusercontent.com/assets/5233052/25921862/f1fc036e-358b-11e7-988f-381971f1608b.png)

**Comment by resgraph** [comment]
In addition to the text area not being, the comment count was not updated after a comment was added. Simple fix is to replace the current post with comments, with the updated post with comments. Commit #8f542a6 implements this change. Pushed to heroku.
